config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]

  resources :products

  resources :racks, only: :index
  resources :offices, only: :index
  resources :schools, only: :index
 

  
  root "statics#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :admin
 
  has_many_attached :pics
  validates :pics, presence: true, blob: { content_type: :image }

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

    def index

    end

    def show

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
    def index
        @metal_offices = Product.where(furniture_style: "Metal_Office_Furniture").order(created_at: :desc).page(params[:page]).per(5)
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_admin!, except: [:index, :show]
    before_action :set_product, except: %i[new create index]    

    def index
        @products = Product.all.order(created_at: :desc).page(params[:page]).per(5)
    end

    def new
        @product = current_admin.products.build
    end

    def create
        @product = current_admin.products.build(products_params)
        if @product.save
            redirect_to root_path, notice: "Product Created"
        else
            redirect_to new_admin_session_path, alert: "Error"
        end
    end

    def edit

    end

    def update
        if @product.update(products_params)
            redirect_to root_path, notice: "Product Updated"
        end
    end

    def destroy
        if @product.destroy
            redirect_to root_path, notice: "Product Removed"
        end
    end

    def show

    end

    private

        def set_product
            @product = Product.find(params[:id])
        end

        def products_params
            params.require(:product).permit(:admin_id, :name, :description, :furniture_style, :price, pics: [])
        end
    

end

app/controllers/racks_controller.rb
class RacksController < ApplicationController
    def index
        @metal_racks = Product.where(furniture_style: "Metal_Racks_Furniture").order(created_at: :desc).page(params[:page]).per(5)
    end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
    def index
        @metal_schools = Product.where(furniture_style: "Metal_School_Furniture").order(created_at: :desc).page(params[:page]).per(5)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController 
    def home
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_custom_css(key)
        case key
        when "notice" then "alert alert-primary"
        when "alert" then "alert alert-danger"
        end
    end

    def active?(path)
        "active" if current_page?(path)
    end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class=" d-flex align-items-center justify-content-center <%= flash_custom_css(key) %> gap-3 m-0" data-controller="flash" style="background: #ffc506;">
        <%= value %>
        <button data-action="flash#dismiss" class="d-flex align-items-center justify-content-center" style="background: none; border: none; width: 2rem; margin: 0px; height: 2rem;">
            <svg xmlns="http://www.w3.org/2000/svg" style="height: 1rem; width: 1rem;" viewBox="0 0 384 512"><path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"/></svg>
        </button>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark">
  <div class="container-fluid">
    <small class="navbar-brand text-white" style="display: flex; justify-content: center; align-items: center; background: transparent; margin: 0; border: 0; color: white;">Asra Metal Works</small>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse mx-3 gap-3" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link navbar-hov", style:"display: flex; justify-content: center; align-items: center; background: transparent; margin: 0; border: 0; color: white;"%>
        </li>
        <li class="nav-item ">
          <%= link_to "Browse", products_path, class:"nav-link text-white navbar-hov", style:"display: flex; justify-content: center; align-items: center; background: transparent; margin: 0; border: 0; color: white;" %>
        </li>
      </ul>

      <div class=" d-flex mx-3 gap-3" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-end">
        <li class="nav-item">
          <% unless current_admin %>
            <%= link_to "Admin", new_admin_session_path, class:"nav-link navbar-hov", style:"display: flex; justify-content: center; align-items: center; background: transparent; margin: 0; border: 0;"%>
          <% end %>
        </li>
      </ul>
      </div>

        <% if current_admin %>
            
            <li>
                <%= button_to "Sign Out", destroy_admin_session_path, method: :delete, class:"btn btn-primary", style:"margin-bottom: 20px;" %>
            </li>

            <li >
                <%= link_to "Add A Product", new_product_path, class:"text-white", style:"text-decoration: none;" %>
            </li>
      
        <% end %>
      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/_section.html.erb
<section class="py-5 text-center" style="background-color: #eee;">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light ">Products and Services</h1>
            <p class="lead ">Asra Metal Works provides you the best range of metal racks furniture, office metal furniture & metal school furniture with effective & timely delivery.</p>
            <p>
                <%= link_to "Metal Racks Furnitures", racks_path, class:"btn btn-primary my-2 #{active?(racks_path)}"%>
                <%= link_to "Metal Office Furnitures", offices_path, class:"btn btn-primary my-2 #{active?(offices_path)}"%>
                <%= link_to "Metal School Furnitures", schools_path, class:"btn btn-primary my-2 #{active?(schools_path)}"%>
            </p>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsraApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="page-animate">
    <%= render "layouts/navbar"%>
    <%= render "layouts/flash_messages"%>
    <%= yield %>
  </body>
  <footer class="flex-shrink-0 py-4 bg-dark text-white-50">

    <div class="container">
       <div class="row gy-4 gx-5">
          <div class="col">
              <h5 class="h1 text-white">Asra Metal Works</h5>
              <p class="small" style="font-size:15px; color:white;">Behind Tiny Pearls School 2nd Cross Khaja Colony, Gulbarga, Kalaburagi-585104, Karnataka, India</p>
              <p class="small" style="font-size:13px; color:white;"> Contact Us &#9990; 998-656-6610</p>
          </div>

          <div class="col">
            <h3 style="color:white;">Quick Links</h3>
            <ul>
              <li><%= link_to 'Products', products_path, style:" color: white; text-decoration: none;" %></li>
            </ul>
          
          </div>
        </div>
    </div> 
  </footer>
</html>

app/views/offices/index.html.erb
<%= render "layouts/section" %>
<hr class="m-0">
<%= render "products/products", products: @metal_offices%>

app/views/products/_form.html.erb
<%= form_with(model: [product]) do |form| %>
    
    <div class="row">
        <div class="col col-md-3">
            <%= form.label :name %>
            <%= form.text_field :name, class:"form-control", required: true %>
        </div>

        <div class="col col-md-3">
            <%= form.label :price %>
            <%= form.number_field :price, class:"form-control", required: true %>
        </div>

    </div>
    
    <div class="row">
        <div class="col">
            <%= form.label :description %>
            <%= form.text_area :description, class:"form-control", required: true %>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <%= form.file_field :pics, multiple: true, class:"my-3", id: "files-upload", required: true %>
        </div>
    </div>


    <div class="row">
        <div class="col col-md-3">
            <%= form.label :furniture_style %>
            <%= form.select :furniture_style, ['Metal_Racks_Furniture', 'Metal_Office_Furniture', 'Metal_School_Furniture'], { prompt: 'Select' }, class:"form-select", required: true %>
        </div>
    </div>

    <div class="row">
        <div class="col">
        <%= form.submit "Create Product", class:" my-4 btn btn-primary" %>
        </div>
    </div>



<% end %>

app/views/products/_products.html.erb
<section style="background-color: #eee;">
<% products.each do |product| %>
  <div class="container py-5">
    <div class="row justify-content-center mb-3">
      <div class="col-md-12 col-xl-10">
        <div class="card shadow-0 border rounded-3 fade-in-image">
          <div class="card-body">
            <div class="row">
              <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                <div class="bg-image hover-zoom ripple rounded ripple-surface">
                  <%= image_tag product.pics[0], class:"w-100" %>
                  <a href="#!">
                    <div class="hover-overlay">
                      <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-6">
                <h5><%= product.name %></h5>
                
                <div class="mt-1 mb-0 text-muted small">
                  <span><%= product.furniture_style %></span>
                  <span class="text-primary"> • </span>
                  <span>Light weight</span>
                  <span class="text-primary"> • </span>
                  <span>Best finish<br /></span>
                </div>
                <div class="mb-2 text-muted small">
                  <span>Unique design</span>
                  <span class="text-primary"> • </span>
                </div>
                <p class="text-truncate mb-4 mb-md-0">
                  <%= product.description %>
                </p>
              </div>
              <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">
                <div class="d-flex flex-row align-items-center mb-1">
                  <h4 class="mb-1 me-1"><%= product.price %> &#8377;</h4>
                </div>
                <h6 class="text-success">Including GST.</h6>
                <div class="d-flex flex-column mt-4">

                  <%= link_to "View Details", product_path(product), class:"btn btn-primary btn-sm"%>
                  <% if current_admin %>
                    <%= link_to "Edit", edit_product_path(product), class:"btn btn-outline-primary btn-sm mt-2"%>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate products %>
</section>

app/views/products/edit.html.erb
<%= form_for @product do |form| %>
    <h1 class="text-center my-4">Edit Product</h1>
    <div class="container">
        <div class="row">
            <div class="col col-md-3">
                <%= form.label :name %>
                <%= form.text_field :name, class:"form-control", required: true%>
            </div>

            <div class="col col-md-3">
                <%= form.label :price %>
                <%= form.number_field :price, class:"form-control" , required: true%>
            </div>

        </div>

        <div class="row">
            <div class="col">
                <%= form.label :description %>
                <%= form.text_area :description, class:"form-control", required: true %>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-3">
                <%= form.label :furniture_style %>
                <%= form.select :furniture_style, ['Metal_Racks_Furniture', 'Metal_Office_Furniture', 'Metal_School_Furniture'], { prompt: 'Select' }, class:"form-select" , required: true%>
            </div>
        </div>

        <div class="row">
            <div class="col">
            <%= form.submit "Edit Product", class:" mt-3 btn btn-primary" %>
            </div>
        </div>
    </div>


<% end %>

app/views/products/index.html.erb
<%= render "layouts/section" %>
<hr class="m-0">


<%= render "products/products", products: @products %>

app/views/products/new.html.erb
<div class="container">
    <h1 class="text-center">Add A Product</h1>
    <%= render "products/form", product: @product%>
</div>

app/views/products/show.html.erb
<div class="container">
    <div class="flex">
    <hr>
        <div style="margin-top: 50px;" class="d-flex flex-row">
            <div id="product<%=@product.id%>_images" class="carousel slide" data-bs-ride="carousel" style="width: 400px">
                <div class="carousel-inner">
                    <% @product.pics.each_with_index do |img, i| %>
                    <div class="carousel-item <%= i==0 ? 'active' : '' %>" style="height: 25rem;">
                        <%= image_tag img, class:"d-block w-100", style:"max-height: 100%; object-fit: cover;" %>
                    </div>
                    <% end %>
                </div>

                <div class="carousel-indicators" style="position:static;">
                    <% @product.pics.each_with_index do |img, i| %>
                        <button type="button" data-bs-target="#@product<%=@product.id%>_images" data-bs-slide-to="<%= i %>" class="bg-dark <%= i==0 ? 'active' : '' %>" <%= i==0 ? 'aria-current="true"' : "" %> aria-label="Slide <%= i+1 %>"></button>
                    <% end %>
                </div>

                <button class="carousel-control-prev" type="button" data-bs-target="#product<%=@product.id%>_images" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon bg-dark rounded-circle" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#product<%=@product.id%>_images" data-bs-slide="next">
                    <span class="carousel-control-next-icon bg-dark rounded-circle"  aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
                </div>
            </div>

            <div class="mx-4">
                <h2 class="mt-3"><%= @product.name %></h2>
                <hr>
                <div class="mt-5">
                    <h3 class="mb-3">Price: <%= @product.price %> &#8377;</h3>
                    <b>Description: </b><p class="lead"><i><%= @product.description %></i></p>
                    <ul class="list-unstyled">
                        <ul>
                            <li>
                                <%= @product.furniture_style.delete("_") %>
                            </li>
                        </ul>
                    </ul>
                    
                    <div class="d-flex flex-column w-20">
                        <small class="text-muted">Contact Now:</small>
                        <a href="tel:998-656-6610" class="btn btn-primary" style="width: 140px;">
                            998-656-6610
                        </a>
                        <%= link_to "Back", :back, class:"btn btn-outline-primary my-4", style:"width: 70px;"%>
                    </div>
                </div>
                
        </div>
        </div>
        <hr class="m-0">
        
    </div>

</div>

app/views/racks/index.html.erb
<%= render "layouts/section" %>
<hr class="m-0">
<%= render "products/products", products: @metal_racks %>

app/views/schools/index.html.erb
<%= render "layouts/section" %>
<hr class="m-0">
<%= render "products/products", products: @metal_schools%>

app/views/statics/home.html.erb
<header>
    <div
        id="sapna-xerox"
        class="p-223 text-center bg-image"
        style="background-image: url('https://levstal.com/wp-content/uploads/2021/01/carousel-about-1.jpg');
        background-size: cover; height: 692px;">
        
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.7); height: 692px;">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white container">
            <h1 class="mb-3 animate-txt fw-bold">Asra Metal Works</h1>
            <h5 class="mb-4">Best & Qualitative Metal Products In Gulbarga.</h5>

            <div class="d-flex justify-content-center align-items-center">
                <%= link_to 'View Products', products_path, class:"navbar-hov", style:"text-decoration: none; display: flex; justify-content: center; align-items: center; background: transparent; margin: 0; border: 0; color: white;" %>
            </div>
            
          
            </div>
        </div>
        </div>
    </div>
    <!-- Background image -->
</header>